In [33]:
import numpy as np

# actions. 0 -> stay; 1-> up/down ; 2->left/right

h = np.array([0.6, 0.2, 0.2]) #hare actions
p = np.zeros(shape=(3,3))
states = ["V", "H", "D", "S"]
p[0] = np.array([1, 0, 0])
p[1] = np.array([0.2, 0.8, 0])
p[2] = np.array([0.2, 0, 0.8])

P = np.zeros(shape=(3,4,4))
# s is one of (V, H, D, S)
# a is one of (0, 1, 2)
def move(s, a):
    if a == 0:
        return s
    if s == "V":
        if a == 1:
            return "S"
        if a == 2:
            return "D"
        
    if s == "H":
        if a == 1:
            return "D"
        if a == 2:
            return "S"
        
    if s == "D":
        if a == 1:
            return "H"
        if a == 2:
            return "V"
        
    if s == "S":
        if a == 1:
            return "V"
        if a == 2:
            return "H"
        
    return "ERROR"


for a in range(3):
    for s in states:
        #s = origin state
        for h_action in range(h.shape[0]):
            hare_prob = h[h_action]
            for w_action in range(p[a].shape[0]):
                wolf_prob = p[a, w_action]
                P[a, states.index(s), states.index(move(move(s, h_action), w_action))] += hare_prob*wolf_prob
    
            
for row in  P[1]:
    print("[%s]" % (' '.join('%04s' % i for i in row)))
    
c = np.array([[1], [1], [1], [0]])
summ = 0
x = np.array([1, 0, 0, 0])
print(np.dot(x, P[1]))
for i in range(10000):
    summ += np.dot(np.dot(x, np.linalg.matrix_power(P[1], i)),c)*0.99**i
    print(summ)

[0.28 0.16 0.04 0.52]
[0.16 0.28 0.52 0.04]
[0.04 0.52 0.28 0.16]
[0.52 0.04 0.16 0.28]
[ 0.28  0.16  0.04  0.52]
[ 1.]
[ 1.4752]
[ 2.1573496]
[ 2.82094097]
[ 3.51434804]
[ 4.20765985]
[ 4.90330159]
[ 5.59564495]
[ 6.28389392]
[ 6.96670712]
[ 7.64363483]
[ 8.31432351]
[ 8.97863085]
[ 9.63648471]
[ 10.28787401]
[ 10.93281663]
[ 11.57134993]
[ 12.20352164]
[ 12.82938578]
[ 13.44899966]
[ 14.06242239]
[ 14.66971385]
[ 15.27093415]
[ 15.8661433]
[ 16.45540097]
[ 17.03876644]
[ 17.61629847]
[ 18.18805531]
[ 18.75409466]
[ 19.31447366]
[ 19.8692489]
[ 20.4184764]
[ 20.96221164]
[ 21.50050953]
[ 22.03342445]
[ 22.56101022]
[ 23.08332013]
[ 23.60040694]
[ 24.11232289]
[ 24.61911967]
[ 25.12084849]
[ 25.61756002]
[ 26.10930444]
[ 26.59613141]
[ 27.07809011]
[ 27.55522923]
[ 28.02759695]
[ 28.495241]
[ 28.9582086]
[ 29.41654653]
[ 29.87030108]
[ 30.31951809]
[ 30.76424292]
[ 31.20452051]
[ 31.64039532]
[ 32.07191138]
[ 32.49911228]
[ 32.92204118]
[ 33.34074078]
[ 33.75525339]
[ 34.16562087]
[ 34