In [5]:
import numpy as np

# actions. 0 -> stay; 1-> up/down ; 2->left/right

h = np.array([0.6, 0.2, 0.2]) #hare actions
p = np.zeros(shape=(3,3))
states = ["V", "H", "D", "S"]
p[0] = np.array([1, 0, 0])
p[1] = np.array([0.2, 0.8, 0])
p[2] = np.array([0.2, 0, 0.8])

P = np.zeros(shape=(3,4,4))
# s is one of (V, H, D, S)
# a is one of (0, 1, 2)
def move(s, a):
    if a == 0:
        return s
    if s == "V":
        if a == 1:
            return "S"
        if a == 2:
            return "D"
        
    if s == "H":
        if a == 1:
            return "D"
        if a == 2:
            return "S"
        
    if s == "D":
        if a == 1:
            return "H"
        if a == 2:
            return "V"
        
    if s == "S":
        if a == 1:
            return "V"
        if a == 2:
            return "H"
        
    return "ERROR"


for a in range(3):
    for s in states:
        #s = origin state
        for h_action in range(h.shape[0]):
            hare_prob = h[h_action]
            for w_action in range(p[a].shape[0]):
                wolf_prob = p[a, w_action]
                P[a, states.index(s), states.index(move(move(s, h_action), w_action))] += hare_prob*wolf_prob
    
            
for row in  P[1]:
    print("[%s]" % (' '.join('%04s' % i for i in row)))
    
c = np.array([[1], [1], [1], [0]])
#print(np.dot(x, P[1]))
summ = 0
J = np.zeros(4)
for x in range(4):
    X = np.zeros(4)
    X[x] = 1
    summ = 0
    for i in range(10000):
        summ += np.dot(np.dot(X, np.linalg.matrix_power(P[0], i)),c)*(0.99**i)
    J[x] = summ
print(J)
I = np.identity(4)
# X * (I - y*P)^-1 * C
print( np.dot(np.dot(I, np.linalg.inv(I - 0.99*P[0])), c))

[0.28 0.16 0.04 0.52]
[0.16 0.28 0.52 0.04]
[0.04 0.52 0.28 0.16]
[0.52 0.04 0.16 0.28]
[ 75.3117207   75.3117207   75.9198064   73.45675221]
[[100.]
 [100.]
 [100.]
 [  0.]]
