In [1]:
import numpy as np
states = ["11", "12", "13", "14", "21", "22", "23", "24", "31", "32", "33", "34", "41", "42", "43", "44"]
moves = [(2, 3), (1, 4), (1, 4), (3, 2)]
actions = ["left", "right", "up", "down", "stay"]

def move(action, pos):
    if action == "left" or action == "right":
        if pos % 2 == 0:
            return pos-1
        else:
            return pos +1
    if action == "up" or action == "down":
        if pos < 3:
            return pos+2
        else:
            return pos -2
    return pos


    
Pstay = np.zeros(shape=(16,16))
Pleft = np.zeros(shape=(16,16))
Pright = np.zeros(shape=(16,16))
Pup = np.zeros(shape=(16,16))
Pdown = np.zeros(shape=(16,16))
cost = np.ones(shape=(16,5))
for w in range(1,5):
    for h in range(1,5):
        for m in moves[h-1]:
            Pstay[states.index(str(w)+str(h)), states.index(str(w)+str(m))] = 0.5 * 0.4
        Pstay[states.index(str(w)+str(h)), states.index(str(w)+str(h))] = 0.6
            
for w in range(1,5):
    for h in range(1,5):
        for m in moves[h-1]:
            Pleft[states.index(str(w)+str(h)), states.index(str(move("left",w))+str(m))] = 0.8 * 0.5*0.4
            Pleft[states.index(str(w)+str(h)), states.index(str(w)+str(m))] = 0.2 * 0.5*0.4
        Pleft[states.index(str(w)+str(h)), states.index(str(move("left",w)) + str(h))] = 0.8 * 0.6
        Pleft[states.index(str(w)+str(h)), states.index(str(w) + str(h))] = 0.2 * 0.6
            
for w in range(1,5):
    for h in range(1,5):
        for m in moves[h-1]:
            Pright[states.index(str(w)+str(h)), states.index(str(move("right",w))+str(m))] = 0.8 * 0.5*0.4
            Pright[states.index(str(w)+str(h)), states.index(str(w)+str(m))] = 0.2 * 0.5*0.4
        Pright[states.index(str(w)+str(h)), states.index(str(move("right",w))+str(h))] = 0.8 * 0.6
        Pright[states.index(str(w)+str(h)), states.index(str(w)+str(h))] = 0.2 * 0.6
            
for w in range(1,5):
    for h in range(1,5):
        for m in moves[h-1]:
            Pup[states.index(str(w)+str(h)), states.index(str(move("up",w))+str(m))] = 0.8 * 0.5*0.4
            Pup[states.index(str(w)+str(h)), states.index(str(w)+str(m))] = 0.2 * 0.5*0.4
        Pup[states.index(str(w)+str(h)), states.index(str(move("up",w))+str(h))] = 0.8 * 0.6
        Pup[states.index(str(w)+str(h)), states.index(str(w)+str(h))] = 0.2 * 0.6
            
for w in range(1,5):
    for h in range(1,5):
        for m in moves[h-1]:
            Pdown[states.index(str(w)+str(h)), states.index(str(move("down",w))+str(m))] = 0.8 * 0.5*0.4
            Pdown[states.index(str(w)+str(h)), states.index(str(w)+str(m))] = 0.2 * 0.5*0.4
        Pdown[states.index(str(w)+str(h)), states.index(str(move("down",w))+str(h))] = 0.8 * 0.6
        Pdown[states.index(str(w)+str(h)), states.index(str(w)+str(h))] = 0.2 * 0.6

for row in  Pup:
    print("[%s]" % (' '.join('%06s' % i for i in row)))
    
print(Pstay[1], Pstay[4], Pstay[11], Pstay[14])

[  0.12   0.04   0.04    0.0    0.0    0.0    0.0    0.0   0.48   0.16   0.16    0.0    0.0    0.0    0.0    0.0]
[  0.04   0.12    0.0   0.04    0.0    0.0    0.0    0.0   0.16   0.48    0.0   0.16    0.0    0.0    0.0    0.0]
[  0.04    0.0   0.12   0.04    0.0    0.0    0.0    0.0   0.16    0.0   0.48   0.16    0.0    0.0    0.0    0.0]
[   0.0   0.04   0.04   0.12    0.0    0.0    0.0    0.0    0.0   0.16   0.16   0.48    0.0    0.0    0.0    0.0]
[   0.0    0.0    0.0    0.0   0.12   0.04   0.04    0.0    0.0    0.0    0.0    0.0   0.48   0.16   0.16    0.0]
[   0.0    0.0    0.0    0.0   0.04   0.12    0.0   0.04    0.0    0.0    0.0    0.0   0.16   0.48    0.0   0.16]
[   0.0    0.0    0.0    0.0   0.04    0.0   0.12   0.04    0.0    0.0    0.0    0.0   0.16    0.0   0.48   0.16]
[   0.0    0.0    0.0    0.0    0.0   0.04   0.04   0.12    0.0    0.0    0.0    0.0    0.0   0.16   0.16   0.48]
[  0.48   0.16   0.16    0.0    0.0    0.0    0.0    0.0   0.12   0.04   0.04    0.0    